#!/bin/bash

docker compose --profile msmtest down
docker compose --profile testing down

# Main switch for handling different commands
case $1 in 
    "test")
        # Nested switch for handling specific test environments
        case $2 in
            "local")
                docker compose --profile msmtest up --detach
                docker-compose logs -f "msm"
                ;;
            "container")
                docker build --tag local/test:latest .
                docker compose --profile testing up --detach
                docker-compose logs -f "test"
                ;;
            *)
                echo "Usage: msm test [local | container]"
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Usage: msm test [local | container]"
        exit 1
        ;;
esac
