#!/bin/bash

function down {
    docker compose --profile msmtest down
    docker compose --profile testing down
    docker image prune -f
    docker volume prune -f
}

# Main switch for handling different commands
case $1 in 
    "test")
        # Shut down related running containers
        down

        case $2 in
            "local")
                docker compose --profile msmtest up --detach
                docker-compose logs -f "msm"
                ;;
            "container")
                docker build --tag local/test:latest .
                docker compose --profile testing up --detach
                docker-compose logs -f "test"
                ;;
            *)
                echo "Usage: msm test [local | container]"
                exit 1
                ;;
        esac
        ;;

    "deploy")
        mv ./configurations/openApi/* ./docs
        ;;

    "down")
        down
        ;;

    *)
        echo "Usage: msm [test | deploy]"
        exit 1
        ;;
esac
